-- premake5.lua
-- generated by muhhae

workspace "CPPTemplate"
    configurations { "Debug", "Release" }

SRCDIR = "src" --Source Code Directory
BUILDDIR = "bin" --Build Directory
OBJDIR = "obj" --Obj Directory
RESFILE = "resource" --Resource Directory
OUT = "%{cfg.buildcfg}-%{prj.name}"

VK = "D:/Other/VulkanSDK" --Vulkan SDK directory
VKLIB = "%{VK}/Lib"
VKINC = "%{VK}/Include"


project "App"
    kind "ConsoleApp" --App Type
    language "C++" --Languange

    cppdialect "C++latest"
    links {
        "glfw3", "%{VKLIB}/vulkan-1", "opengl32"
    } --link library

    includedirs {
        VKINC, 
    }

    targetdir "%{BUILDDIR}/%{OUT}" 
    objdir "%{OBJDIR}/%{OUT}"

    files {
        "%{SRCDIR}/**.h",
        "%{SRCDIR}/**.hpp", 
        "%{SRCDIR}/**.cpp",

    }

    prebuildcommands { 
        "rm -rf %{BUILDDIR}/%{OUT}/resource",
        "{COPYDIR} %{RESFILE} %{BUILDDIR}/%{OUT}/resource" 
    }

    filter "configurations:Debug"
        defines { "DEBUG" }
        symbols "On"

    filter "configurations:Release"
        defines { "NDEBUG" }
        optimize "On"