-- premake5.lua
-- generated by muhhae

workspace "CPPTemplate"
    configurations { "Debug", "Release" }

SRCDIR = "src" --Source Code Directory
BUILDDIR = "bin" --Build Directory
OBJDIR = "obj" --Obj Directory
RESFILE = "resource" --Resource Directory
OUT = "%{cfg.buildcfg}-%{prj.name}"

VK = "D:/Other/VulkanSDK" --Vulkan SDK directory
VKLIB = "%{VK}/Lib"
VKINC = "%{VK}/Include"

-- GLFW3 = "" --glfw3 directory
-- GLFWLIB = "%{GLFW3}/Lib"
-- GLFWLIB = "%{GLFW3}/Include"

project "App"
    language "C++" --Languange

    cppdialect "C++latest"
    links {
        "glfw3", --change to %{GLFWLIB}/glfw3 if glfw3 is not in the default path 
        "%{VKLIB}/vulkan-1",
        "opengl32"
    } 

    includedirs {
        VKINC, 
    }

    targetdir "%{BUILDDIR}/%{OUT}" 
    objdir "%{OBJDIR}/%{OUT}"

    files {
        "%{SRCDIR}/**.h",
        "%{SRCDIR}/**.hpp", 
        "%{SRCDIR}/**.cpp",
    }

    filter "configurations:Debug"
        kind "ConsoleApp" --App Type
        defines { "DEBUG" }
        symbols "On"

    filter "configurations:Release"
        kind "WindowedApp" --App Type
        defines { "NDEBUG" }
        optimize "On"
        prebuildcommands { 
            "rm -rf %{BUILDDIR}/%{OUT}/resource",
            "{COPYDIR} %{RESFILE} %{BUILDDIR}/%{OUT}/resource" 
        }